### ISSUE TITLE
Waveform accuracy

### ISSUE THREAD

**Issue by neilcornish** [vallis/kissreport#1]
For the waveform accuracy I suggest adding the comment that for the systematic error to be below the statistical error we need the mis-match to be less than D/(2 SNR^2), where D is the number of parameters in the waveform. The reference is 

@article{Chatziioannou:2016ezg,
      author         = "Chatziioannou, Katerina and Klein, Antoine and Cornish,
                        Neil and Yunes, Nicolas",
      title          = "{Analytic Gravitational Waveforms for Generic Precessing
                        Binary Inspirals}",
      journal        = "Phys. Rev. Lett.",
      volume         = "118",
      year           = "2017",
      number         = "5",
      pages          = "051101",
      doi            = "10.1103/PhysRevLett.118.051101",
      eprint         = "1606.03117",
      archivePrefix  = "arXiv",
      primaryClass   = "gr-qc",
      SLACcitation   = "%%CITATION = ARXIV:1606.03117;%%"
}

**Comment by vallis** [comment]
Added, thanks.
