### ISSUE TITLE
Understanding unknown GW signals

### ISSUE THREAD

**Issue by neilcornish** [vallis/kissreport#2]
There is a new paper on this topic that I think we should reference. We showed that the difference in phasing for glitches and signals in the TDI variables will allow us to distinguish unmodeled gravitational wave burst from instrument glitches. It is just a first stab at the problem, and a lot more work has to be done, but it is at least a start.

@article{Robson:2018jly,
      author         = "Robson, Travis and Cornish, Neil J.",
      title          = "{Detecting Gravitational Wave Bursts with LISA in the
                        presence of Instrumental Glitches}",
      journal        = "Phys. Rev.",
      volume         = "D99",
      year           = "2019",
      number         = "2",
      pages          = "024019",
      doi            = "10.1103/PhysRevD.99.024019",
      eprint         = "1811.04490",
      archivePrefix  = "arXiv",
      primaryClass   = "gr-qc",
      SLACcitation   = "%%CITATION = ARXIV:1811.04490;%%"
}

**Comment by vallis** [comment]
Interesting! Reference added.
