### ISSUE TITLE
Parallel computing

### ISSUE THREAD

**Issue by neilcornish** [vallis/kissreport#5]
In the discussions (with Anne, Travis, Curt and others) we talked about parallel architectures for stochastic computing. One theme was that parallel tempering can be completely asynchronous, so with thousands of chains running in parallel there should always be pairs that can propose swaps. Another theme was mixed CPU/GPU architectures with GPUs being able to do e.g. wavelet or FFTs for likelihood calculation.

**Comment by vallis** [comment]
This appears already in the discussion, but I've made it more prominent.
